### PR TITLE
Praetor app docs edit added to the Akash Docs

### PR DESCRIPTION
**Pull request by oiclid**

### CODE REVIEW

**Comment by HoomanDigital** [comment]
Please consider to sync your branch with main, you pr seems to be deleting a line from sequence.ts which is important:

image

**Comment by oiclid** [comment]
@HoomanDigital Fixed.

**Comment by HoomanDigital** [comment]
@andy108369 @chainzero : please take a look at this PR, this adds an additional documentation specially around praetor..

thanks

**Comment by HoomanDigital** [comment]
@oiclid it seems you have completely removed the sequence.ts changes, please consider adding index to sequence.ts

**Comment by oiclid** [comment]
@HoomanDigital updating didn't seem to be working, so I just simply copied the contents of the sequence.ts from the main Akash branch and pasted it in there. The change would most likely be from there.

**Pull request merged**
