### PR TITLE
Fixed the issues #152 and #153

### PR DESCRIPTION
**Pull request by hiroyukikumazawa**

### CODE REVIEW

**Comment by hiroyukikumazawa** [comment]
Fixed the [issue #152](https://github.com/akash-network/website/issues/152) and [issue #153](https://github.com/akash-network/website/issues/153)
We can test here - [Akash docs](http://65.109.84.205:4321/docs/)

**Comment by ghost** [comment]
LGTM for the issue #152 
Waiting for the confirmation for #153 => https://github.com/akash-network/website/issues/153#issuecomment-2074628802

**Comment by ghost** [comment]
@hiroyukikumazawa It is best if you split this PR into two separate ones, that way I could merge the one that solves #152

**Comment by hiroyukikumazawa** [comment]
@andy108369 splitted this PR to #159

**Pull request closed without merging**
