### PR TITLE
Broken docs links_2024-07-11

### PR DESCRIPTION
**Pull request by oiclid**

### CODE REVIEW

**Comment by HoomanDigital** [comment]
@oiclid can you please elaborate the changes? I see no changes but you have deleted one file completely. (https://akash.network/docs/guides/helium-validator/)

**Comment by oiclid** [comment]
> @oiclid can you please elaborate the changes? I see no changes but you have deleted one file completely. (https://akash.network/docs/guides/helium-validator/)

`Helium` doesn't run a testnet anymore. They have not done so for at least two years. That guide is obsolete. Sorry for the late reply. I've been traveling. @HoomanDigital

**Comment by HoomanDigital** [comment]
@oiclid thanks for creating this PR.

your pr have some conflicts, can you please resolve the conflicts on your end?

thanks

**Comment by oiclid** [comment]
@HoomanDigital The missing helium validator file is the problem. Like I said, I deleted it because it’s of no use anymore. I reached out to the Helium team and they told me the validator has not been active for a couple of years, which is why I deleted it. I don't think I have write access, so I can't do that myself. Can you help merge it?

**Pull request merged**
