### PR TITLE
Implement tab option

### PR DESCRIPTION
**Pull request by hiroyukikumazawa**
GPU Pricing, Usage Pricing Calculator.

image

### CODE REVIEW

**Comment by hiroyukikumazawa** [comment]
For issue https://github.com/akash-network/website/issues/252
@aktdenis, @HoomanHQ, I'd love to hear your feedbacks.

**Comment by HoomanDigital** [comment]
Thanks @hiroyukikumazawa for the PR, this issue is still under discussion..  We will take a call after finalization of direction.

**Comment by HoomanDigital** [comment]
Closing this for a time being..

**Comment by hiroyukikumazawa** [comment]
ok

**Pull request closed without merging**
