### PR TITLE
Added icons to menu item Network (dropdown)

### PR DESCRIPTION
**Pull request by hiroyukikumazawa**
for the issue https://github.com/akash-network/website/issues/34

### CODE REVIEW

**Comment by hiroyukikumazawa** [comment]
we can review here
http://65.109.84.205:4321/

**Comment by aktdenis** [comment]
thanks @hiroyukikumazawa appreciate your effort, but we would need to use different icons. i believe we used these across the website; https://github.com/iconoir-icons/iconoir

cc @HoomanHQ

**Comment by hiroyukikumazawa** [comment]
@aktdenis 
I can't see any icons of https://github.com/iconoir-icons/iconoir
otherwise I can see @heroicons/react - https://heroicons.com/
May I use this?

**Comment by aktdenis** [comment]
@hiroyukikumazawa you're right, sorry. i know we've been talking about these two sets. feel free to use heroicons

**Comment by hiroyukikumazawa** [comment]
http://65.109.84.205:4321/
Please check again here @HoomanHQ, @aktdenis

**Comment by hiroyukikumazawa** [comment]
image
image

**Comment by hiroyukikumazawa** [comment]
Before:
image

After:
image

**Comment by aktdenis** [comment]
@hiroyukikumazawa thank you for you effort. as we discussed [here](https://github.com/akash-network/website/issues/250) - there are several issues to resurface some of the pages on the website - we need to rethink the whole menu experience. i'll provide a draft and combine related issues into one

**Comment by hiroyukikumazawa** [comment]
> @hiroyukikumazawa thank you for you effort. as we discussed [here](https://github.com/akash-network/website/issues/250) - there are several issues to resurface some of the pages on the website - we need to rethink the whole menu experience. i'll provide a draft and combine related issues into one

ok

**Comment by hiroyukikumazawa** [comment]
ok, please let me know if there is any updates

**Comment by HoomanDigital** [comment]
closing this now due to irrelevancy and plan to revamp everything going forward. thanks

**Pull request closed without merging**
