### PR TITLE
UX updates

### PR DESCRIPTION
**Pull request by piber-dev**
add desired functionality from issue 389,
update text, add buttoms, from mockup found on issue 389, 
fix references to events page,

https://github.com/akash-network/website/issues/389

### CODE REVIEW

**Comment by piber-dev** [comment]
added UI/design plus text from figma,
changed functionality of sort function to sort by date but not group cards into months,
note: TBD events currently show before other events, LMK if this is not the intended sorting method and i can place them last

**Comment by HoomanDgtl** [comment]
Thanks, @piber-dev, for submitting the PR. After review, we have the following feedback:

1. The UI is not responsive on both mobile and tablet versions. It breaks on various screen sizes, lacking proper attention to detail.
2. The design appears to have been implemented with only a 14-inch screen in mind. We request that you ensure it is 100% responsive, properly expanding on larger screens while maintaining high responsiveness on smaller ones.
3. Also, please ensure that the CTAs and text on the cards remain unchanged.

attaching some images below:
image
image


here is the test link to review the implementation: https://akashnetworkwebsite-git-fo-d02dd4-dharamveers-projects-33277843.vercel.app/community/events/

cc @aktdenis

thanks

**Comment by piber-dev** [comment]
hello @HoomanDgtl, thanks for your review.

> The UI is not responsive on both mobile and tablet versions. It breaks on various screen sizes, lacking proper attention to detail.
> 
> The design appears to have been implemented with only a 14-inch screen in mind. We request that you ensure it is 100% responsive, properly expanding on larger screens while maintaining high responsiveness on smaller ones.

this is correct, i only applied the figma design and after writing to @aktdenis privately, we wanted to try with fixed widths like the design included there but did not know whether or not mobile support was required. my testing concluded that any width over ~600px looked good. i will look into this and create a commit after resolving the issue.

> After a second review, we noticed that some CTAs have been misdirected. For example, the AI World Congress link is redirecting to Token2049, and similar issues exist with other cards.
> 
> We recommend keeping the text and CTAs unchanged. This issue is solely related to UI updates, and any modifications to the text or links are not acceptable.

i don't think this issue is related to my PR. while this issue exists on the test link, it also is an issue on live link and should be treated as a seperate issue. because i see this on the live link as well, i will assume nothing is wrong on my end but let me know if you see any examples where there are differences in link/text or anything else between main link and test link. see images below with link in the bottom left corner. to me this looks like someone added this event card without finishing it? but please let me know if i'm wrong.
image
image

**Comment by aktdenis** [comment]
thanks @HoomanDgtl for the review.

@piber-dev there seems to be a misunderstanding. i thought you were referring to the column's fixed width. We definitely need to include mobile responsiveness, just like the previous page had it.

along with responsiveness, we got to ensure all the links, texts and CTAs are correct. 

are you comfortable implementing the required updates?

appreciate the work you have done so far

**Comment by piber-dev** [comment]
update: 

i re-used some of the old styling for the grids making it support up to 4 columns again and got rid of the fixed widths altogether. the issues should be fully resolved now. here are some mobile resolutions from different iphones, pixel 7, and ipad. i also tested resolutions 1920x1080, 360x800, 1366x768, and 1536x864 plus responsive and it looks to be working as intended from approximately 200px width to as wide as i could test across two monitors and zoomed out. i will make a commit for this in a few minutes.

image
image
image
image

**Comment by piber-dev** [comment]
hi @aktdenis, thanks for your response

> @piber-dev there seems to be a misunderstanding. i thought you were referring to the column's fixed width. We definitely need to include mobile responsiveness, just like the previous page had it.

definitely, sorry about this. i was too fixed up making it look exactly like the figma file but it should be a mix of the figma file and the old page in the commit i am making now, without using fixed widths or modifying a lot of the page.

> are you comfortable implementing the required updates?

i have completed the mentioned issues with responsiveness and mobile support in the commit i will be making now. in my opinion the issue related to texts and links being wrong is unrelated as these are already on the main branch from almost a year ago (e.g. [this file](https://github.com/akash-network/website/blob/main/src/content/Community_Akash_Events_Page/ai-world-congress/index.md)). i don't know enough of these events to update the text and think this should be apart of a cleanup effort by the events working group, not an effort in an UI/UX issue.

**Comment by piber-dev** [comment]
commit is done, please review this and my previous comments when you have the opportunity

CC: @HoomanDgtl

thanks!

**Comment by HoomanDgtl** [comment]
thanks @piber-dev : lets move tbd events to the end.
And add a horizontal line separation just above the footer as in homepage..  (this horizontal line should be after the cta 'explore past events', for reference check homepage footer..)

thanks

**Comment by HoomanDgtl** [comment]
@piber-dev please also add redirects in astro.config file for the following links:

/community/events/upcoming => /community/events

thanks

**Comment by piber-dev** [comment]
hi @HoomanDgtl thanks for another review,

> thanks @piber-dev : lets move tbd events to the end.

done. TBD dates are now sorted to be at the end of the list and TBD locations are sorted by their date. the original a.month & b.month sorting that was in place didn't work for TBD so switching it to a.tbd and b.tbd did the trick. i removed TBD sorting altogether from the archived.astro file as TBD events will not even make it that far.

> And add a horizontal line separation just above the footer as in homepage.. (this horizontal line should be after the cta 'explore past events', for reference check homepage footer..)

done. i found how it worked and used the same color as found in the deploy.astro file. it would make sense to have this color be in the config but i just copied how that file was for now, if any effort is to be made making consistent color naming it's easy to search and replace all in VS Code. i saw a lot of instances where this color code was used so lets keep it as is for now.

> @piber-dev please also add redirects in astro.config file for the following links:
>
> /community/events/upcoming => /community/events

i assume this refers to the `redirects.ts` file, i added it now and the redirect worked after restarting the development server.

**Comment by HoomanDgtl** [comment]
Thanks @piber-dev, we have the defined border color in place:
image


However, the spacing below the border is currently double what it should be. Could you please adjust the spacing to match the borderline as seen on the homepage?

Everything else looks good.

Thanks!

**Comment by piber-dev** [comment]
hi @HoomanDgtl i was unable to do it from within the files i have been working on but if i add a border-b to the layout.astro file and remove the bottom border from the CTA.astro file it gets added consistently to every page. without it, only the pages with the deploy.astro file seems to have this border added correctly. it looks like this line should not be included specifically for the overhaul of this page but i'm happy to contribute.

feel free to proceed with these changes. before these changes, there is not consistently a border at the bottom on many pages. after this change, it is consistent whether or not the page uses the deploy.astro file. note that some pages such as the akash-insiders page looks weird after this because it has a horizontal line going maybe 80% of the screen which is not seen on other pages, plus the 100% line after this change.

other solutions can be adding the deploy.astro file to the events pages but in my opinion this is making the page too cluttered as there is already the deploy now button in the corner and a lot of information on that page already.

**Pull request merged**
