### PR TITLE
Home page refinement with detailings and implementation of missing components

### PR DESCRIPTION
**Pull request by HoomanHQ**
## Summary

We have worked on refining the codebase of the homepage while keeping the existing layout intact. We have also added advanced and responsive components with detailing in all the elements, ensuring proper margin, padding and also we have implemented missing components like: footer, connect with community etc..

The following changes have been made to the homepage:

- There is infinite-console error in the current website due to a buggy element, we have found the issue behind this and fixed in this pull request (Now there will be no error in the console following this PR)
- Improved responsiveness to work flawlessly in all screen sizes.
- Refined the design of all components with detailing.
- Ensured proper margin and padding for a more polished appearance.
- Implemented the "Connect with Community" feature, footer, and menu bar, along with refining other components.

Additionally, this pull request resolves the following issues:

- Resolves issue #201
- Resolves issue #194

## Basic Example

You can review the live changes in action through this link: [Live Link](https://website-xkb34kn8d-hoomanhq-s-team.vercel.app/) 
## Motivation

Our primary motivation for this initiative is to enhance the professionalism and organization of the Akash website. Currently, we have identified several areas where the coding practices fall short of adhering to fundamental principles, resulting in a disorganized codebase with excessive inline CSS usage instead of proper classes and folders. As a consequence, the website lacks complete responsiveness and experiences issues on custom screen sizes, such as tablets.

To address these challenges, we have worked on homepage while preserving its existing layout. Our focus was on introducing advanced and responsive components with meticulous detailing to ensure proper margin and padding. By doing so, we have implemented more polished appearance and seamless user experience across all devices.

This endeavor holds immense importance for both future contributors and the long-term validation of the Akash team's plan. By implementing a well-organized codebase, we provide clarity and ease for future contributors to understand the existing structure and functionality. This, in turn, empowers them to seamlessly build upon the code, introduce new features, and resolve issues without encountering confusion. As a result, the development process gains momentum, and contributors can confidently deliver high-quality contributions.

Furthermore, a well-structured codebase contributes to the long-term sustainability and success of the Akash. It allows for scalability, adaptability, and easier maintenance as the project evolves over time. The team can make informed decisions, refine the project's direction, and consistently deliver a polished and professional product.

In summary, prioritizing complete responsiveness, ui/ux refinement with detailing and code organization not only supports the efforts of future contributors but also ensures the successful and sustainable trajectory of the Akash.

To reaffirm our dedication to these goals:
> our vision is outlined in issue #209, and the implementation of the homepage aligns precisely with this vision.

## Checks

- [x] Supports all screen sizes (if relevant)
- [x] Supports both light and dark mode (if relevant)
- [x] Passes `npm run test`

### CODE REVIEW

**Comment by HoomanHQ** [comment]
cc @anilmurty @brewsterdrinkwater @aktdenis @zachhorn 

Please review.

While reviewing: if any issue is there in our implementation: please let us know, we will fix. Thank you

**Comment by HoomanHQ** [comment]
> thank you. sizing images for the blogs seems to be off. Should the design of those banners be a different size?
> 
> For the "Connect with the Community" Section there is a graphic with some words like "Ai", "GPU" etc. If you click, is anything intended to happen. If there is no call to action, can these words be removed?
> 
> Screen Shot 2023-08-07 at 10 22 15 AM

Sure: we will fix the following thing. 
> blog image sizes will be fixed 
> Those words will be removed from the graphic (connect with community)

**Comment by HoomanHQ** [comment]
cc @brewsterdrinkwater 

Issues fixed: 
> Addressed blog image size issue
> Added CTA's to the graphic in 'Connect with community section'

Latest link to review changes: https://website-1havspqan-hoomanhq-s-team.vercel.app/


Thanks

**Comment by HoomanHQ** [comment]
> on the footer, there is some spacing issues on the left side on desktop.
> 
> Can the copy be left aligned under the logo mark?
> Screen Shot 2023-08-08 at 10 54 30 AM

yep

**Comment by HoomanHQ** [comment]
> on the footer, there is some spacing issues on the left side on desktop.
> 
> Can the copy be left aligned under the logo mark?
> Screen Shot 2023-08-08 at 10 54 30 AM

cc @brewsterdrinkwater 

issue fixed, you can check here: https://website-xkb34kn8d-hoomanhq-s-team.vercel.app/

**Comment by aktdenis** [comment]
Here are couple of my observations:
Screenshot 2023-08-09 at 15 32 00

1. Two buttons with different labels, but have the same functionality. Might be confusing for the users. 
- There are some things to consider (cloudmos,console, praetor) for this action and will be resolved in a draft I'll share tomorrow during wg meet.
2. Dark mode icon seems to be heavier than the rest of the icons
3. I do like the more prominent black headline, but the subheadline should have a breakpoint defined so there not only two words left in the second line.
4. Documentations button should be more subtle, maybe different secondary color (gray). 
5. Open-source tag, could be much smaller, subtle. We might move it to the footer only.

Screenshot 2023-08-09 at 15 32 37
1. I prefer the existing version where groups are switching on scroll so there is no need for additional clicks. 

Screenshot 2023-08-09 at 15 32 48
1. Animation is nice, but I think it doesn't fit to the rest of the UI. You could have a look in the figma file provided for web design guidelines. 

Screenshot 2023-08-09 at 15 33 01
1. The graphic is nice, but those floating words seems like they are clickable. I do agree we need a Community CTA, got a draft will share tomorrow during wg. 

Screenshot 2023-08-09 at 15 33 14
1. It would be nice to have some consistency on the buttons. Either fully rounded, 6px, 8px - whatever... but use the same on all. 

Screenshot 2023-08-09 at 15 33 47
1. It looks like the footer is flexing across the whole width. Would be great if it has the same margins as the rest of the content. All rights reserved should be left or right aligned - when centered it seems like it just floating around. Also, the logo used, is not the Akash logo. 

We can discuss further steps tomorrow during wg-meet. Ty!🙏🏼

**Comment by HoomanHQ** [comment]
cc @aktdenis : please review at: https://website-c2ld4cgdu-hoomanhq-s-team.vercel.app/

**Pull request closed without merging**
