### PR TITLE
docs: added content for getting started > into to akash

### PR DESCRIPTION
**Pull request by tgrecojs**

### CODE REVIEW

**Comment by tgrecojs** [comment]
meant to mark this as ready for review last night (in the spirit of getting things out in smaller commits)

**Comment by tgrecojs** [comment]
@HoomanHQ i've updated this branch to contain the proper text. Each jumplink from the prior version of this file has been added to the table, however, one of the links is connected to a "broken resource".

I didn't want to point the link to the incorrect section, so if you could edit the file with the correct info then that would be great. Otherwise, you could also let me know where the link should point to, then i have no issue updating it myself

**Comment by tgrecojs** [comment]
@hoomanHQ I'm realizing that I misunderstood the differecne between jumplink vs. regular link. I haven't changed any of the title text though. 

I did update the last section's title to be a h3 header, as opposed to the bold text representation that has been used. 

let me know if there are any issues with this though and i'll see that i get them squared (although I think it should be g2g).

**Comment by HoomanDigital** [comment]
Closing this PR due to no further activity or actions..

**Pull request closed without merging**
