### PR TITLE
Guides 2

### PR DESCRIPTION
**Pull request by oiclid**
Edits to hosting, data viz, and ML guides

### CODE REVIEW

**Comment by HoomanDgtl** [comment]
under review...

**Comment by HoomanDgtl** [comment]
@oiclid : plzz report back once you are done with the implementation

**Comment by oiclid** [comment]
@HoomanDgtl what implementation ?

**Comment by HoomanDgtl** [comment]
I mean: let us know once you are done with this pr, so we can review..

thanks

**Comment by oiclid** [comment]
@HoomanDgtl oh. I am done, for now.

**Pull request merged**
