### PR TITLE
Guides 2

### PR DESCRIPTION
**Pull request by oiclid**

### CODE REVIEW

**Comment by HoomanDgtl** [comment]
under review

**Review by ghost — APPROVED** [review]
LGTM

Branch conflicts need to be resolved though before it can be merged.

**Comment by HoomanDgtl** [comment]
@oiclid could you please resolve the conflicts

**Comment by HoomanDgtl** [comment]
@oiclid : are you still active on this PR? 

thanks

**Comment by oiclid** [comment]
@HoomanDgtl @andy108369 Sorry, I was not reading my notifications. Let me fix it.

**Comment by oiclid** [comment]
@HoomanDgtl @andy108369 Done

**Review by ghost — APPROVED** [review]
@HoomanDgtl looks good for merging.

**Comment by HoomanDgtl** [comment]
There is build error on this PR: 
image

**Pull request merged**
