### PR TITLE
chore: add Bitpanda to token page

### PR DESCRIPTION
**Pull request by hiroyukikumazawa**
refs: #278

### CODE REVIEW

**Comment by HoomanDigital** [comment]
+ please add upbit as per instructions

**Comment by HoomanDigital** [comment]
1. upbit link: https://upbit.com/exchange?code=CRIX.UPBIT.KRW-AKT
2. bitpanda link: https://www.bitpanda.com/en/prices/akash-akt

cc @hiroyukikumazawa 

thanks

**Comment by hiroyukikumazawa** [comment]
@HoomanDigital please check again

**Comment by HoomanDigital** [comment]
thanks @hiroyukikumazawa : this is approved now..

**Pull request merged**
