### PR TITLE
Added URI(s) section under STEP 7

### PR DESCRIPTION
**Pull request by hiroyukikumazawa**

### CODE REVIEW

**Comment by hiroyukikumazawa** [comment]
for https://github.com/akash-network/website/issues/124

**Review by ghost — CHANGES_REQUESTED** [review]
Hey @hiroyukikumazawa !

It wouldn't hurt leaving the Forwarded ports as-is though. Along with the newly added URI(s) section. 
That way one can quickly refer to that image when one needs to point out where one needs to be looking for to locate the forwarded (mapped) ports.

**Comment by hiroyukikumazawa** [comment]
> Hey @hiroyukikumazawa !
> 
> It wouldn't hurt leaving the Forwarded ports as-is though. Along with the newly added URI(s) section. That way one can quickly refer to that image when one needs to point out where one needs to be looking for to locate the forwarded (mapped) ports.

Ok

**Comment by hiroyukikumazawa** [comment]
@andy108369 please review again.
Thank you.

**Comment by hiroyukikumazawa** [comment]
> @hiroyukikumazawa : It seems that you added the image as requested, but you also need to mention the image path in the Markdown file of the docs.

I have replaced the image.
Which markdown file have you mentioned? @HoomanHQ

**Comment by hiroyukikumazawa** [comment]
> @hiroyukikumazawa as mentioned by @andy108369 : could you plzz keep the previous image as in and implement new image as additional image instead of replacement?

ok, no problem

**Comment by hiroyukikumazawa** [comment]
updated @HoomanHQ, @andy108369 .
please check again

**Comment by hiroyukikumazawa** [comment]
@HoomanHQ @andy108369 ,
Is this right? - http://65.109.84.205:4321/docs/deployments/cloudmos-deploy/

**Pull request merged**
